# Generated by Django 5.0 on 2023-12-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='image',
            field=models.ImageField(upload_to='slide/', verbose_name='слайд'),
        ),
    ]
